---
- name: Test setup
  hosts: all
  become: true
  tasks:
    - name: Install a cron daemon
      ansible.builtin.package:
        name: cron
        update_cache: true
        state: present
      when: ansible_facts["os_family"] == "Debian"

    - name: Install a cron daemon
      ansible.builtin.package:
        name: cronie
        state: present
      when: ansible_facts["os_family"] == "RedHat"

- name: Converge
  hosts: all
  become: true
  vars:
    backup_restic_password: "swordfish"
    backup_restic_repository: "/tmp/backup"
  roles:
    - role: blackieops.backup
