---
name: Molecule Tests
'on':
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: blackieops.backup

jobs:
  molecule:
    name: Molecule
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        distro:
          - rockylinux9
          - ubuntu2204
          - debian12

    steps:
      - uses: actions/checkout@v3
        with:
          path: blackieops.backup

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install ansible-lint
        run: pip3 install ansible ansible-lint

      - name: Run ansible-lint
        run: ansible-lint

      - name: Install molecule dependencies
        run: pip3 install molecule molecule-plugins[docker] docker

      - name: Run molecule tests
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
