---
name: Molecule Tests
'on':
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: blackieops.backup

jobs:
  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - rockylinux8
          - ubuntu2004
          - debian11

    steps:
      - uses: actions/checkout@v3
        with:
          path: blackieops.backup

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install test dependencies.
        run: pip3 install ansible molecule[docker] docker

      - name: Run Molecule tests.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
